/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkRouteImport } from './routes/work'
import { Route as RecruiterRouteImport } from './routes/recruiter'
import { Route as PreviewRouteImport } from './routes/preview'
import { Route as CvRouteImport } from './routes/cv'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CIndexRouteImport } from './routes/c/index'
import { Route as CCodeRouteImport } from './routes/c/$code'
import { Route as ApiReferralWebhookRouteImport } from './routes/api/referral/webhook'
import { Route as ApiReferralUnsubscribeRouteImport } from './routes/api/referral/unsubscribe'

const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterRoute = RecruiterRouteImport.update({
  id: '/recruiter',
  path: '/recruiter',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewRoute = PreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const CvRoute = CvRouteImport.update({
  id: '/cv',
  path: '/cv',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CIndexRoute = CIndexRouteImport.update({
  id: '/c/',
  path: '/c/',
  getParentRoute: () => rootRouteImport,
} as any)
const CCodeRoute = CCodeRouteImport.update({
  id: '/c/$code',
  path: '/c/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReferralWebhookRoute = ApiReferralWebhookRouteImport.update({
  id: '/api/referral/webhook',
  path: '/api/referral/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReferralUnsubscribeRoute = ApiReferralUnsubscribeRouteImport.update({
  id: '/api/referral/unsubscribe',
  path: '/api/referral/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/cv': typeof CvRoute
  '/preview': typeof PreviewRoute
  '/recruiter': typeof RecruiterRoute
  '/work': typeof WorkRoute
  '/c/$code': typeof CCodeRoute
  '/c/': typeof CIndexRoute
  '/api/referral/unsubscribe': typeof ApiReferralUnsubscribeRoute
  '/api/referral/webhook': typeof ApiReferralWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/cv': typeof CvRoute
  '/preview': typeof PreviewRoute
  '/recruiter': typeof RecruiterRoute
  '/work': typeof WorkRoute
  '/c/$code': typeof CCodeRoute
  '/c': typeof CIndexRoute
  '/api/referral/unsubscribe': typeof ApiReferralUnsubscribeRoute
  '/api/referral/webhook': typeof ApiReferralWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/cv': typeof CvRoute
  '/preview': typeof PreviewRoute
  '/recruiter': typeof RecruiterRoute
  '/work': typeof WorkRoute
  '/c/$code': typeof CCodeRoute
  '/c/': typeof CIndexRoute
  '/api/referral/unsubscribe': typeof ApiReferralUnsubscribeRoute
  '/api/referral/webhook': typeof ApiReferralWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connect'
    | '/cv'
    | '/preview'
    | '/recruiter'
    | '/work'
    | '/c/$code'
    | '/c/'
    | '/api/referral/unsubscribe'
    | '/api/referral/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connect'
    | '/cv'
    | '/preview'
    | '/recruiter'
    | '/work'
    | '/c/$code'
    | '/c'
    | '/api/referral/unsubscribe'
    | '/api/referral/webhook'
  id:
    | '__root__'
    | '/'
    | '/connect'
    | '/cv'
    | '/preview'
    | '/recruiter'
    | '/work'
    | '/c/$code'
    | '/c/'
    | '/api/referral/unsubscribe'
    | '/api/referral/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnectRoute: typeof ConnectRoute
  CvRoute: typeof CvRoute
  PreviewRoute: typeof PreviewRoute
  RecruiterRoute: typeof RecruiterRoute
  WorkRoute: typeof WorkRoute
  CCodeRoute: typeof CCodeRoute
  CIndexRoute: typeof CIndexRoute
  ApiReferralUnsubscribeRoute: typeof ApiReferralUnsubscribeRoute
  ApiReferralWebhookRoute: typeof ApiReferralWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter': {
      id: '/recruiter'
      path: '/recruiter'
      fullPath: '/recruiter'
      preLoaderRoute: typeof RecruiterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview': {
      id: '/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof PreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cv': {
      id: '/cv'
      path: '/cv'
      fullPath: '/cv'
      preLoaderRoute: typeof CvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/': {
      id: '/c/'
      path: '/c'
      fullPath: '/c/'
      preLoaderRoute: typeof CIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$code': {
      id: '/c/$code'
      path: '/c/$code'
      fullPath: '/c/$code'
      preLoaderRoute: typeof CCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/referral/webhook': {
      id: '/api/referral/webhook'
      path: '/api/referral/webhook'
      fullPath: '/api/referral/webhook'
      preLoaderRoute: typeof ApiReferralWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/referral/unsubscribe': {
      id: '/api/referral/unsubscribe'
      path: '/api/referral/unsubscribe'
      fullPath: '/api/referral/unsubscribe'
      preLoaderRoute: typeof ApiReferralUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnectRoute: ConnectRoute,
  CvRoute: CvRoute,
  PreviewRoute: PreviewRoute,
  RecruiterRoute: RecruiterRoute,
  WorkRoute: WorkRoute,
  CCodeRoute: CCodeRoute,
  CIndexRoute: CIndexRoute,
  ApiReferralUnsubscribeRoute: ApiReferralUnsubscribeRoute,
  ApiReferralWebhookRoute: ApiReferralWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
